// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvommfckswffrkdvzvmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2b21tZmNrc3dmZnJrZHZ6dm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTM1NTIsImV4cCI6MjA2NTU2OTU1Mn0.W_GRyScdXTEf2I6qdgSXR7FP1G0Mr32bCjhRFAQ8tGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);